version: '3.8'

services:
  # Frontend UI service
  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
  
  # Backend API service (FastAPI)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
      - ollama
  
  # Neo4j Database for Knowledge Graph
  neo4j:
    image: neo4j:5.9.0
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
  
  # Ollama for LLM (Mistral)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    command: serve
  
  # Web Scraping Service
  scraper:
    build: ./scraper
    volumes:
      - ./data:/app/data
    environment:
      - OUTPUT_DIR=/app/data/scraped

volumes:
  neo4j_data:
  ollama_models:
  
# Note: You'll need to create the following directories:
# - frontend/ - For your HTML/CSS/JS frontend
# - backend/ - For your FastAPI application
# - scraper/ - For your BeautifulSoup/Scrapy scraping service
# - data/scraped/ - For storing scraped content 